/* YOUR IMAGES — newest at the top. The only file you edit day-to-day.
   Optional extra fields (ignored by the field + grid pages):
     cutout:true   — this work has a transparent background; include it on the cutouts page
     invert:true   — it's dark ink, so flip it to light there so it reads on the dark ground */
const WORKS = [
  { src:"images/bo.png",  title:"pylon bo",   year:"2026" },
  { src:"images/bp.png",  title:"pylon bp",   year:"2026" },
  { src:"images/bq.png",  title:"pylon bq",   year:"2026" },
  { src:"images/br.png",  title:"pylon br",   year:"2026" },
  { src:"images/bs.png",  title:"pylon bs",   year:"2026" },
  { src:"images/bt.png",  title:"pylon bt",   year:"2026" },
  { src:"images/bu.png",  title:"pylon bu",   year:"2026" },
  { src:"images/bv.png",  title:"pylon bv",   year:"2026" },
  { src:"images/ar.png",  title:"pylon ar",   year:"2026" },
  { src:"images/as.png",  title:"pylon as",   year:"2026" },
  { src:"images/at.png",  title:"pylon at",   year:"2026" },
  { src:"images/au.png",  title:"pylon au",   year:"2026" },
  { src:"images/av.png",  title:"pylon av",   year:"2026" },
  { src:"images/aw.png",  title:"pylon aw",   year:"2026" },
  { src:"images/ax.png",  title:"pylon ax",   year:"2026" },
  { src:"images/ay.png",  title:"pylon ay",   year:"2026" },
  { src:"images/az.png",  title:"pylon az",   year:"2026" },
  { src:"images/ba.png",  title:"pylon ba",   year:"2026" },
  { src:"images/bb.png",  title:"pylon bb",   year:"2026" },
  { src:"images/bc.png",  title:"pylon bc",   year:"2026" },
  { src:"images/bd.png",  title:"pylon bd",   year:"2026" },
  { src:"images/be.png",  title:"pylon be",   year:"2026" },
  { src:"images/bf.png",  title:"pylon bf",   year:"2026" },
  { src:"images/bg.jpeg", title:"pylon bg",   year:"2026" },
  { src:"images/bh.jpeg", title:"pylon bh",   year:"2026" },
  { src:"images/bi.jpeg", title:"pylon bi",   year:"2026" },
  { src:"images/bj.jpeg", title:"pylon bj",   year:"2026" },
  { src:"images/bk.jpeg", title:"pylon bk",   year:"2026" },
  { src:"images/bl.jpeg", title:"pylon bl",   year:"2026" },
  { src:"images/bm.jpeg", title:"pylon bm",   year:"2026" },
  { src:"images/bn.jpeg", title:"pylon bn",   year:"2026" },
  { src:"images/1.2.png", title:"pylon 12",    year:"2026" },
  { src:"images/3.2.png", title:"pylon 32",    year:"2026" },
  { src:"images/4.3.png", title:"lattice i",   year:"2026" },
  { src:"images/2.2.png", title:"lattice ii",  year:"2026" },
  { src:"images/7.2.png", title:"chaos bloom", year:"2026" },
  { src:"images/8.2.png", title:"vertebrae",   year:"2026" },
  { src:"images/a.png",   title:"pylon a",     year:"2026" },
  { src:"images/b.png",   title:"pylon b",     year:"2026" },
  { src:"images/c.png",   title:"pylon c",     year:"2026" },
  { src:"images/d.png",   title:"pylon d",     year:"2026" },
  { src:"images/e.png",   title:"pylon e",     year:"2026" },
  { src:"images/f.png",   title:"pylon f",     year:"2026" },
  { src:"images/g.png",   title:"pylon g",     year:"2026" },
  { src:"images/h.jpeg",  title:"pylon h",     year:"2026" },
  { src:"images/i.jpeg",  title:"pylon i",     year:"2026" },
  { src:"images/j.png",   title:"pylon j",     year:"2026", cutout:true, invert:true },
  { src:"images/k.png",   title:"pylon k",     year:"2026", cutout:true },
  { src:"images/l.png",   title:"pylon l",     year:"2026", cutout:true, invert:true },
  { src:"images/m.png",   title:"pylon m",     year:"2026", cutout:true },
  { src:"images/n.png",   title:"pylon n",     year:"2026", cutout:true },
  { src:"images/o.png",   title:"pylon o",     year:"2026" },
  { src:"images/p.png",   title:"pylon p",     year:"2026" },
  { src:"images/q.png",   title:"pylon q",     year:"2026" },
  { src:"images/r.png",   title:"pylon r",     year:"2026" },
  { src:"images/s.png",   title:"pylon s",     year:"2026" },
  { src:"images/t.png",   title:"pylon t",     year:"2026" },
  { src:"images/u.png",   title:"pylon u",     year:"2026" },
  { src:"images/v.png",   title:"pylon v",     year:"2026" },
  { src:"images/w.png",   title:"pylon w",     year:"2026" },
  { src:"images/x.png",  title:"pylon x",     year:"2026" },
  { src:"images/y.png",  title:"pylon y",     year:"2026" },
  { src:"images/z.PNG",   title:"pylon z",     year:"2026" },
  { src:"images/aa.png",   title:"pylon aa",     year:"2026" },
  { src:"images/ab.png",   title:"pylon ab",     year:"2026" },
  { src:"images/ac.jpeg",   title:"pylon ac",     year:"2026" },
  { src:"images/ad.jpeg",   title:"pylon ad",     year:"2026" },
  { src:"images/ae.png",   title:"pylon ae",     year:"2026" },
  { src:"images/af.png",   title:"pylon af",     year:"2026" },
  { src:"images/ag.png",   title:"pylon ag",     year:"2026" },
  { src:"images/ah.png",   title:"pylon ah",     year:"2026", cutout:true, invert:true },
  { src:"images/ai.png",   title:"pylon ai",     year:"2026", cutout:true, invert:true },
  { src:"images/aj.png",   title:"pylon aj",     year:"2026", cutout:true, invert:true },
  { src:"images/ak.png",   title:"pylon ak",     year:"2026", cutout:true, invert:true },
  { src:"images/al.png",   title:"pylon al",     year:"2026" },
  { src:"images/am.png",   title:"pylon am",     year:"2026" },
  { src:"images/an.png",   title:"pylon an",     year:"2026" },
  { src:"images/ao.png",   title:"<3",     year:"2026" },
  { src:"images/ap.png",   title:"pylon ap",     year:"2026" },
  { src:"images/aq.png",   title:"pylon aq",     year:"2026" },
];
