#!/usr/bin/env bash
# ==================================================================
# make-thumbs.sh — generate images/thumbs/ from the originals.
#
# The originals in images/ are the artworks and are never touched.
# This script writes downscaled derivatives (max 1400px on the long
# side) that the pages use inline; the lightbox always loads the
# original. It also writes images/thumbs/index.js, the manifest the
# site reads to know which thumb belongs to which original.
#
# Opaque images become JPEG (much smaller); images with an alpha
# channel stay PNG so transparency survives. If an original has no
# manifest entry the site silently falls back to the original file,
# so forgetting to run this never breaks anything — it just costs
# bandwidth.
#
# Needs only macOS's built-in `sips`. Run from anywhere:
#   ./tools/make-thumbs.sh
# ==================================================================
set -euo pipefail
cd "$(dirname "$0")/.."

MAX=1400
JPEG_QUALITY=82
mkdir -p images/thumbs

manifest=""
count=0

for f in images/*.png images/*.PNG images/*.jpg images/*.JPG images/*.jpeg images/*.JPEG; do
  [ -e "$f" ] || continue
  base=$(basename "$f")
  name="${base%.*}"

  # the background texture is handled separately below
  [ "$base" = "texture.png" ] && continue

  alpha=$(sips -g hasAlpha "$f" | awk '/hasAlpha/{print $2}')
  w=$(sips -g pixelWidth  "$f" | awk '/pixelWidth/{print $2}')
  h=$(sips -g pixelHeight "$f" | awk '/pixelHeight/{print $2}')
  long=$(( w > h ? w : h ))

  if [ "$alpha" = "yes" ]; then out="images/thumbs/$name.png"; else out="images/thumbs/$name.jpg"; fi

  if [ ! -f "$out" ] || [ "$f" -nt "$out" ]; then
    if [ "$alpha" = "yes" ]; then
      if [ "$long" -gt "$MAX" ]; then
        sips -Z "$MAX" "$f" --out "$out" >/dev/null
      else
        cp "$f" "$out"
      fi
    else
      if [ "$long" -gt "$MAX" ]; then
        sips -Z "$MAX" -s format jpeg -s formatOptions "$JPEG_QUALITY" "$f" --out "$out" >/dev/null
      else
        sips -s format jpeg -s formatOptions "$JPEG_QUALITY" "$f" --out "$out" >/dev/null
      fi
    fi
    echo "  made $out ($(du -h "$out" | cut -f1 | tr -d ' ') from $(du -h "$f" | cut -f1 | tr -d ' '))"
  fi

  # a thumb only earns its place by being smaller than the original;
  # otherwise the site just serves the original (the code's fallback)
  if [ "$(stat -f %z "$out")" -ge "$(stat -f %z "$f")" ]; then
    rm -f "$out"
    echo "  skipped $base — original is already small"
    continue
  fi

  manifest+="  \"$base\": \"$(basename "$out")\","$'\n'
  count=$((count + 1))
done

{
  echo "/* GENERATED by tools/make-thumbs.sh — do not edit by hand. */"
  echo "window.THUMBS = {"
  printf '%s' "$manifest"
  echo "};"
} > images/thumbs/index.js

echo "wrote images/thumbs/index.js ($count entries)"
