#!/usr/bin/env bash
# ==================================================================
# make-thumbs.sh — generate images/thumbs/ from the originals.
#
# The originals in images/ are the artworks and are never touched.
# This script writes downscaled derivatives (max 1400px on the long
# side) that the pages use inline; the lightbox always loads the
# original. It also writes images/thumbs/index.js, the manifest the
# site reads to know which thumb belongs to which original.
#
# Opaque images become JPEG (much smaller); images with an alpha
# channel stay PNG so transparency survives. If an original has no
# manifest entry the site silently falls back to the original file,
# so forgetting to run this never breaks anything — it just costs
# bandwidth.
#
# Uses macOS's built-in `sips`, or dispatches to the native
# PowerShell implementation when run from Git Bash on Windows.
# Run from anywhere:
#   ./tools/make-thumbs.sh
# ==================================================================
set -euo pipefail

script_dir=$(cd "$(dirname "$0")" && pwd)

case "${OS:-}:${OSTYPE:-}" in
  Windows_NT:*|*:msys*|*:cygwin*)
    ps_script="$script_dir/make-thumbs.ps1"
    if command -v cygpath >/dev/null 2>&1; then
      ps_script=$(cygpath -w "$ps_script")
    fi

    if command -v pwsh >/dev/null 2>&1; then
      exec pwsh -NoProfile -File "$ps_script"
    elif command -v powershell.exe >/dev/null 2>&1; then
      exec powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$ps_script"
    fi

    echo "error: Windows PowerShell 5.1 or PowerShell 7 is required" >&2
    exit 1
    ;;
esac

if ! command -v sips >/dev/null 2>&1; then
  echo "error: this shell implementation needs macOS sips" >&2
  echo "on Windows, run tools\\make-thumbs.ps1 or use Git Bash" >&2
  exit 1
fi

cd "$script_dir/.."

MAX=1400
JPEG_QUALITY=82
mkdir -p images/thumbs

manifest=""
count=0

while IFS= read -r f; do
  base=$(basename "$f")
  name="${base%.*}"

  alpha=$(sips -g hasAlpha "$f" | awk '/hasAlpha/{print $2}')
  w=$(sips -g pixelWidth  "$f" | awk '/pixelWidth/{print $2}')
  h=$(sips -g pixelHeight "$f" | awk '/pixelHeight/{print $2}')
  long=$(( w > h ? w : h ))

  if [ "$alpha" = "yes" ]; then out="images/thumbs/$name.png"; else out="images/thumbs/$name.jpg"; fi

  if [ ! -f "$out" ] || [ "$f" -nt "$out" ]; then
    if [ "$alpha" = "yes" ]; then
      if [ "$long" -gt "$MAX" ]; then
        sips -Z "$MAX" "$f" --out "$out" >/dev/null
      else
        cp "$f" "$out"
      fi
    else
      if [ "$long" -gt "$MAX" ]; then
        sips -Z "$MAX" -s format jpeg -s formatOptions "$JPEG_QUALITY" "$f" --out "$out" >/dev/null
      else
        sips -s format jpeg -s formatOptions "$JPEG_QUALITY" "$f" --out "$out" >/dev/null
      fi
    fi
    echo "  made $out ($(du -h "$out" | cut -f1 | tr -d ' ') from $(du -h "$f" | cut -f1 | tr -d ' '))"
  fi

  # a thumb only earns its place by being smaller than the original;
  # otherwise the site just serves the original (the code's fallback)
  if [ "$(stat -f %z "$out")" -ge "$(stat -f %z "$f")" ]; then
    rm -f "$out"
    echo "  skipped $base — original is already small"
    continue
  fi

  manifest+="  \"$base\": \"$(basename "$out")\","$'\n'
  count=$((count + 1))
done < <(
  LC_ALL=C find images -maxdepth 1 -type f \
    \( -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' \) \
    ! -iname 'texture.png' -print | LC_ALL=C sort
)

{
  echo "/* GENERATED by tools/make-thumbs.* - do not edit by hand. */"
  echo "window.THUMBS = {"
  printf '%s' "$manifest"
  echo "};"
} > images/thumbs/index.js

echo "wrote images/thumbs/index.js ($count entries)"
